### ISSUE TITLE
Cannot run Ranker.exe, seems to be missing a file

### ISSUE THREAD

**Issue by vjf** [thesgc/TeXRank#1]
Hi Jia,
I cannot run 'Ranker.exe', each time it complains about missing 'UpdatedTextons_10Oct_PrecTextonsLarge_Xtal.mat':

C:\Users\faz014\Desktop\TeXRank-master\TeXRank-master>Ranker.exe FilePaths.txt MA003826 "Background_SubwellA.mat, Background_SubwellC.mat, Background_SubwellD.mat"
Loading files and background images...
Error using load
Unable to read file UpdatedTextons_10Oct_PrecTextonsLarge_Xtal.mat: No such
file or directory.

Error in FD_TFG_HourlyInspection_Console (line 68)

MATLAB:load:couldNotReadFile

Any clues?

Vincent.

**Comment by JiaTsingNg** [comment]
Hi Vincent, 

try downloading the updated file - must have uploaded the old one instead. 

Thanks! Let me know if the same error (or new ones) pops up!
